services:
  eko-cli:
    image: eko-cli
    build: ./
    environment:
      EKO_OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    volumes:
      - eko-data:/.eko
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4318:4318"
      - "8889:8889"

volumes:
  eko-data: